apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"productpage-v1"}]'
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: mesh1-ossm-federation-bookinfo
    meta.helm.sh/release-namespace: teste-bookinfo
  creationTimestamp: "2023-08-15T14:25:18Z"
  generation: 2
  labels:
    app: random-http-traffic-generator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: traffic-generator
    app.openshift.io/runtime: other-linux
  name: random-http-traffic-generator
  namespace: red-bookinfo1-app
  resourceVersion: "60822"
  uid: bf21761e-67c6-4387-a2ff-8a50a3b6caf3
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: random-http-traffic-generator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: random-http-traffic-generator
    spec:
      containers:
      - env:
        - name: ENV_MAXIMUM_RANDOM_WAIT_TIME
          value: "3"
        - name: ENV_CURL_URL
          value: http://istio-ingressgateway-red-mesh-system.apps.cfzky981.eastus.aroapp.io/productpage
        image: quay.io/nebula0248/random-http-traffic-generator:v1.0
        imagePullPolicy: IfNotPresent
        name: random-http-traffic-generator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2023-08-15T14:25:50Z"
    lastUpdateTime: "2023-08-15T14:25:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-08-15T14:25:18Z"
    lastUpdateTime: "2023-08-15T14:26:07Z"
    message: ReplicaSet "random-http-traffic-generator-667d448dc" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
