apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mesh1-ossm-federation-bookinfo
    meta.helm.sh/release-namespace: teste-bookinfo
  creationTimestamp: "2023-08-15T14:25:18Z"
  labels:
    app: reviews
    app.kubernetes.io/managed-by: Helm
    service: reviews
  name: reviews
  namespace: red-bookinfo1-app
  uid: dd33e5a9-6774-4b02-a78b-b8ce903e348a
spec:
  clusterIP: 172.30.202.226
  clusterIPs:
  - 172.30.202.226
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: reviews
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
