apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: details
  namespace: red-bookinfo1-app
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
